swagger: '2.0'
info:
  title: pokemon
  x-ibm-name: pokemon
  version: 1.0.0
  description: >-
    - Obtain Auth0 token using command 

    ```

    curl -s -X POST https://ozairs.auth0.com/oauth/token -H 'Content-Type:
    application/json'  -H 'Host: ozairs.auth0.com' \
      -d '{
        "client_id": "gQrd64uy9zsA6nCyz05DmViy19MziPVq",
        "client_secret": "Dk5gHOz3vJHhl6uIS29z5OJs1JF2cAz_ijoS4U-1B59NHKmVyuc-R7nInc6f6a2h",
        "audience": "ozairs.apiconnect.com",
        "grant_type": "client_credentials"
    }'

    ```
host: $(catalog.host)
schemes:
  - https
basePath: /api
produces:
  - application/json
consumes:
  - application/json
security:
  - clientIdHeader: []
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
    description: ''
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - switch:
          version: 2.0.0
          title: switch
          case:
            - condition: (($httpVerb() = 'GET' and $operationPath() = '/pokemon'))
              execute:
                - invoke:
                    version: 2.0.0
                    title: invoke
                    header-control:
                      type: blacklist
                      values: []
                    parameter-control:
                      type: whitelist
                      values: []
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error:
                      - ConnectionError
                    target-url: 'https://pokemons.mybluemix.net/api/pokemons/'
            - condition: '(($httpVerb() = ''GET'' and $operationPath() = ''/pokemon/{id}''))'
              execute:
                - invoke:
                    version: 2.0.0
                    title: invoke
                    header-control:
                      type: blacklist
                      values: []
                    parameter-control:
                      type: whitelist
                      values: []
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error:
                      - ConnectionError
                    target-url: 'https://pokemons.mybluemix.net/api/pokemons/{id}'
    catch:
      - errors:
          - ConnectionError
          - RuntimeError
        execute:
          - set-variable:
              title: set-variable
              actions:
                - set: message.body
                  value: '{"message": "Error occurred during search operation."}'
                  type: string
              version: 2.0.0
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  properties:
    target-url:
      value: 'http://example.com/operation-name'
      description: The URL of the target service
      encoded: false
parameters:
  Authorization:
    name: Authorization
    type: string
    required: false
    in: header
tags: []
definitions: {}
paths:
  '/pokemon/{id}':
    get:
      responses:
        '200':
          description: 200 OK
      consumes:
        - application/json
      produces:
        - application/json
    parameters:
      - name: id
        type: string
        required: true
        in: path
      - name: Authorization
        type: string
        required: false
        in: header
  /pokemon:
    get:
      responses:
        '200':
          description: 200 OK
      consumes:
        - application/json
      produces:
        - application/json
    post:
      responses:
        '200':
          description: 200 OK
      parameters:
        - $ref: '#/parameters/Authorization'
