swagger: '2.0'
info:
  title: weather
  x-ibm-name: weather
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - switch:
          version: 2.0.0
          title: switch
          case:
            - condition: (($httpVerb() = 'GET' and $operationPath() = '/current'))
              execute:
                - set-variable:
                    version: 2.0.0
                    title: set-variable
                    actions:
                      - set: target-url
                        value: >-
                          https://myweatherprovider.mybluemix.net/current?zipcode=$(request.parameters.zipcode)
                        type: string
            - condition: (($httpVerb() = 'GET' and $operationPath() = '/today'))
              execute:
                - set-variable:
                    version: 2.0.0
                    title: set-variable
                    actions:
                      - set: target-url
                        value: >-
                          https://myweatherprovider.mybluemix.net/today?zipcode=$(request.parameters.zipcode)
                        type: string
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)
  properties:
    target-url:
      value: ''
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  catalogs: {}
basePath: /weather
paths:
  /today:
    get:
      responses:
        '200':
          schema:
            type: string
          description: success
    parameters:
      - name: zipcode
        in: query
        required: false
        type: string
  /current:
    get:
      responses:
        '200':
          schema:
            type: string
          description: success
    parameters:
      - name: zipcode
        in: query
        required: false
        type: string
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
